---

- name: Configure instance(s)
  hosts: dev
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day       

    - name: Install prerequisites for Docker repository
      become: yes
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
    
    - name: add docker apt key
      apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

    - name: add docker apt repo
      apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
          state: present
          update_cache: yes
  
    - name: install docker and its dependencies
      become: yes
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: start and enable containerd daemon
      become: yes
      service:
        name: containerd
        state: started
        enabled: yes	

    - name: Download the PHP application and Docker file from GitHub
      git:
        repo: 'https://partho.sundaram@gmail.com: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@github.com/parthasundaramda/EdurekaProjectRepo.git'
        dest: "/home/edureka/"
            
    - name: Build docker image from docker file
      docker_image:
        name: edurekaProjectImage
        build:
          pull: yes
          path: /home/edureka/EdurekaProjectRepo/Dockerfile
        state: present
        source: build
            
    - name: Launch Docker Container
      docker_container:
        name: edurekaProject
        image: edurekaProjectImage
        state: started
        ports:
          - "22:22"
          - "8888:8888"
